language: php

php:
  - 5.3
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 5.3
    - php: hhvm
  fast_finish: true

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit tests

notifications:
    on_success: never
    on_failure: always